<a href="https://colab.research.google.com/github/welcomeglory/Python/blob/master/07_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
matrix = np.arange(1,13)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
matrix = matrix.reshape(3,4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
matrix>5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
matrix[matrix>5] # 5보다 큰값 뽑아줘

array([ 6,  7,  8,  9, 10, 11, 12])

In [ ]:
matrix[[0,2],:]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
# fancy 인덱싱
m1 = matrix[[0,2],:][:,[0,3]]
m1

array([[ 1,  4],
       [ 9, 12]])

In [ ]:
matrix[0:2,1:3] # 0~1행,1~2열, ':'은 전체 다 출력

array([[2, 3],
       [6, 7]])

In [ ]:
matrix[2,3] # 2행 3열

12

In [ ]:
matrix[:,2]

array([ 3,  7, 11])

In [ ]:
matrix[2,:]

array([ 9, 10, 11, 12])

In [ ]:
# 3행 3열 매트릭스 생성
matrix = [
    [4, 4, 2],
    [6, 4, 5],
    [9, 8, 7]
]
matrix

[[4, 4, 2], [6, 4, 5], [9, 8, 7]]

In [ ]:
# sort(정렬)
sorted = np.sort(matrix, axis=0) # 행기준 정렬
sorted

array([[3, 4, 2],
       [3, 4, 5],
       [9, 8, 7]])

In [ ]:
# sort(정렬)
sorted = np.sort(matrix, axis=1) # 열기준 정렬
sorted

array([[2, 4, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix[::-1] # 행을 역순으

[[9, 8, 7], [6, 4, 5], [4, 4, 2]]

In [ ]:
m1 = np.arange(1,13)
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# 아그솔트
np.argsort(m1, axis=0) # 인덱스를 가져온다.


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
m2 = [10,1,4,8,2,5,7]
m2

[10, 1, 4, 8, 2, 5, 7]

In [ ]:
np.argsort(m2) # 데이터를 정렬한 인덱스 출력

array([1, 4, 2, 5, 6, 3, 0])