<a href="https://colab.research.google.com/github/welcomeglory/Python/blob/master/07_31.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [ ]:
red_path = "/content/drive/MyDrive/세종교육/winequality-red.csv"
white_path ="/content/drive/MyDrive/세종교육/winequality-white.csv"

In [ ]:
red_df = pd.read_csv(red_path, sep=';')
red_df['label'] = 0
red_df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  label  
0         9.4        5      0  
1         9.8        5      0  
2         9.8        5      0  
3         9.8        6      0  
4         9.4        5      0  
...       ...      ...    ...  
1594     10.5        5      0  
1595     11.2        6      0  
1596     11.0        6      0  
1597     10.2        5      0  
1598     11.0        6      0  

[1599 rows x 13 columns]

In [ ]:
white_df = pd.read_csv(white_path, sep=';')
white_df['label'] = 1
white_df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  label  
0         8.8        6      1  
1         9.5        6      1  
2        10.1        6      1  
3         9.9        6      1  
4         9.9        6      1  
...       ...      ...    ...  
4893     11.2        6      1  
4894      9.6        5      1  
4895      9.4        6      1  
4896     12.8        7      1  
4897     11.8        6      1  

[4898 rows x 13 columns]

In [ ]:
wine_df = pd.concat([red_df, white_df])
wine_df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  label  
0         9.4        5      0  
1         9.8        5      0  
2         9.8        5      0  
3         9.8        6      0  
4         9.4        5      0  
...       ...      ...    ...  
4893     11.2        6      1  
4894      9.6        5      1  
4895      9.4        6      1  
4896     12.8        7      1  
4897     11.8        6      1  

[6497 rows x 13 columns]

In [ ]:
wine_df.reset_index(drop=-True, inplace=True)
wine_df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  label  
0         9.4        5      0  
1         9.8        5      0  
2         9.8        5      0  
3         9.8        6      0  
4         9.4        5      0  
...       ...      ...    ...  
6492     11.2        6      1  
6493      9.6        5      1  
6494      9.4        6      1  
6495     12.8        7      1  
6496     11.8        6      1  

[6497 rows x 13 columns]

In [ ]:
matrix = wine_df.values
matrix

array([[ 7.4 ,  0.7 ,  0.  , ...,  9.4 ,  5.  ,  0.  ],
       [ 7.8 ,  0.88,  0.  , ...,  9.8 ,  5.  ,  0.  ],
       [ 7.8 ,  0.76,  0.04, ...,  9.8 ,  5.  ,  0.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  9.4 ,  6.  ,  1.  ],
       [ 5.5 ,  0.29,  0.3 , ..., 12.8 ,  7.  ,  1.  ],
       [ 6.  ,  0.21,  0.38, ..., 11.8 ,  6.  ,  1.  ]])

In [ ]:
x = matrix[:, :-1] # : 전체 행을 가져옴 :-1 마지막번째 전까지만 가져옴
y = matrix[:, -1] # 맨 마지막 필드만 가져옴
print(x)
print(y) # y값 정답

[[ 7.4   0.7   0.   ...  0.56  9.4   5.  ]
 [ 7.8   0.88  0.   ...  0.68  9.8   5.  ]
 [ 7.8   0.76  0.04 ...  0.65  9.8   5.  ]
 ...
 [ 6.5   0.24  0.19 ...  0.46  9.4   6.  ]
 [ 5.5   0.29  0.3  ...  0.38 12.8   7.  ]
 [ 6.    0.21  0.38 ...  0.32 11.8   6.  ]]
[0. 0. 0. ... 1. 1. 1.]


In [ ]:
#
x = (x - x.min(axis=0))/ (x.max(axis=0) - x.min(axis=0))
x

array([[0.29752066, 0.41333333, 0.        , ..., 0.19101124, 0.20289855,
        0.33333333],
       [0.33057851, 0.53333333, 0.        , ..., 0.25842697, 0.26086957,
        0.33333333],
       [0.33057851, 0.45333333, 0.02409639, ..., 0.24157303, 0.26086957,
        0.33333333],
       ...,
       [0.2231405 , 0.10666667, 0.11445783, ..., 0.13483146, 0.20289855,
        0.5       ],
       [0.14049587, 0.14      , 0.18072289, ..., 0.08988764, 0.69565217,
        0.66666667],
       [0.18181818, 0.08666667, 0.22891566, ..., 0.05617978, 0.55072464,
        0.5       ]])

In [ ]:
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size = 0.2, random_state=42)
yTrain = tf.one_hot(yTrain.flatten(), 2)
yTest = tf.one_hot(yTest.flatten(), 2)

In [ ]:
yTrain

<tf.Tensor: shape=(5197, 2), dtype=float32, numpy=
array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)>

In [ ]:
yTest

<tf.Tensor: shape=(1300, 2), dtype=float32, numpy=
array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)>

In [ ]:
diabetes_path = "/content/drive/MyDrive/세종교육/diabetes.csv"

In [ ]:
diabetes_df = pd.read_csv(diabetes_path)
diabetes_df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
# x_df = diabetes_df.iloc[:,:-1].values
# y_df = diabetes_df.iloc[:,-1].values
# print(x_df)
# print(y_df)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0

In [ ]:
matrix = diabetes_df.values
matrix

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [ ]:
x = matrix[:, :-1] # : 전체 행을 가져옴 :-1 마지막번째 전까지만 가져옴
y = matrix[:, -1] # 맨 마지막 필드만 가져옴
print(x)
print(y) # y값 정답

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0.
 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0.
 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0.
 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1.
 1. 0. 

In [ ]:
x = (x - x.min(axis=0))/ (x.max(axis=0) - x.min(axis=0))
x

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [ ]:
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size = 0.2, random_state=42)
yTrain = tf.one_hot(yTrain.flatten(), 2)
yTest = tf.one_hot(yTest.flatten(), 2)

In [ ]:
path = "/content/drive/MyDrive/세종교육/Dataset_SPM_demagnetization.csv"
df = pd.read_csv(path)

In [ ]:
df

T_spec  Rated_speed_spec       Bmr         delta         m  \
0      90.997916       5116.643283  0.487506  39397.195441  1.975955   
1      96.830847       2226.239955  1.117701  37152.332847  1.574790   
2     102.586168       2589.833840  0.818783  18766.047877  2.104074   
3     111.253693       3163.692510  0.528683  22063.089337  2.163076   
4     172.367321       4311.028350  0.949390  33858.425728  1.570513   
...          ...               ...       ...           ...       ...   
6995  159.364113       4749.542270  1.039289  19504.290289  2.030319   
6996  224.651212       2015.725351  0.754173  30060.974368  1.730464   
6997   76.494218       4256.312308  0.833625  19827.664635  1.431976   
6998  137.636142       4606.793403  1.094727  21790.744279  2.204684   
6999  128.671616       2164.505874  0.813261  29548.179826  1.809786   

            so        d0     Lmagn        h4        h3  max_OL  \
0     0.006290  0.000851  0.512480  0.001664  0.003630       0   
1     0.003757  0.001497  8.219508  0.001791  0.003028      11   
2     0.006557  0.001192  1.988612  0.001773  0.003840       3   
3     0.006596  0.001263  0.867449  0.001629  0.002692       0   
4     0.004287  0.001406  3.652513  0.002261  0.002335       3   
...        ...       ...       ...       ...       ...     ...   
6995  0.004891  0.001188  4.427485  0.001844  0.002757       8   
6996  0.004976  0.000800  1.090370  0.001866  0.002935       0   
6997  0.004543  0.001574  2.753413  0.002411  0.003848       5   
6998  0.003779  0.001432  6.948240  0.002315  0.003591      11   
6999  0.006381  0.000872  1.429579  0.001422  0.002403       1   

      max_OL_analytical  
0              1.149800  
1             13.160608  
2              3.702697  
3              0.036690  
4              3.615744  
...                 ...  
6995           9.063788  
6996           0.377823  
6997           5.538668  
6998          15.631949  
6999           0.687960  

[7000 rows x 12 columns]

In [ ]:
matrix = df.values
matrix

array([[9.09979155e+01, 5.11664328e+03, 4.87505920e-01, ...,
        3.63014381e-03, 0.00000000e+00, 1.14980036e+00],
       [9.68308471e+01, 2.22623996e+03, 1.11770054e+00, ...,
        3.02782403e-03, 1.10000000e+01, 1.31606077e+01],
       [1.02586168e+02, 2.58983384e+03, 8.18782847e-01, ...,
        3.84011308e-03, 3.00000000e+00, 3.70269683e+00],
       ...,
       [7.64942178e+01, 4.25631231e+03, 8.33625424e-01, ...,
        3.84788686e-03, 5.00000000e+00, 5.53866841e+00],
       [1.37636142e+02, 4.60679340e+03, 1.09472674e+00, ...,
        3.59120994e-03, 1.10000000e+01, 1.56319493e+01],
       [1.28671616e+02, 2.16450587e+03, 8.13260531e-01, ...,
        2.40295824e-03, 1.00000000e+00, 6.87959549e-01]])

In [ ]:
x = matrix[:, :-1] # : 전체 행을 가져옴 :-1 마지막번째 전까지만 가져옴
y = matrix[:, -1] # 맨 마지막 필드만 가져옴
print(x)
print(y) # y값 정답

[[9.09979155e+01 5.11664328e+03 4.87505920e-01 ... 1.66381856e-03
  3.63014381e-03 0.00000000e+00]
 [9.68308471e+01 2.22623996e+03 1.11770054e+00 ... 1.79133333e-03
  3.02782403e-03 1.10000000e+01]
 [1.02586168e+02 2.58983384e+03 8.18782847e-01 ... 1.77280717e-03
  3.84011308e-03 3.00000000e+00]
 ...
 [7.64942178e+01 4.25631231e+03 8.33625424e-01 ... 2.41073302e-03
  3.84788686e-03 5.00000000e+00]
 [1.37636142e+02 4.60679340e+03 1.09472674e+00 ... 2.31526423e-03
  3.59120994e-03 1.10000000e+01]
 [1.28671616e+02 2.16450587e+03 8.13260531e-01 ... 1.42225540e-03
  2.40295824e-03 1.00000000e+00]]
[ 1.14980036 13.16060767  3.70269683 ...  5.53866841 15.63194932
  0.68795955]


In [ ]:
x = (x - x.min(axis=0))/ (x.max(axis=0) - x.min(axis=0))
x

array([[0.10656189, 0.96209428, 0.05353378, ..., 0.25982611, 0.8000883 ,
        0.        ],
       [0.14546331, 0.13601987, 0.88990316, ..., 0.35091719, 0.51321813,
        1.        ],
       [0.18384713, 0.23993464, 0.49319142, ..., 0.33768289, 0.90009153,
        0.27272727],
       ...,
       [0.00983275, 0.71621254, 0.5128899 , ..., 0.79338976, 0.90379399,
        0.45454545],
       [0.41760502, 0.81637969, 0.85941325, ..., 0.72519095, 0.78154505,
        1.        ],
       [0.35781814, 0.11837633, 0.48586242, ..., 0.08726374, 0.21560984,
        0.09090909]])

In [ ]:
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size = 0.2, random_state=42)
yTrain = tf.one_hot(yTrain.flatten(), 2)
yTest = tf.one_hot(yTest.flatten(), 2)

In [ ]:
print(xTrain.shape)
print(xTest.shape)
print(yTrain.shape)
print(yTest.shape)

(5600, 11)
(1400, 11)
(5600, 2)
(1400, 2)


In [ ]:
df.groupby('max_OL').size()

max_OL
0     1903
1     1211
2      812
3      641
4      526
5      380
6      289
7      257
8      191
9      139
10     128
11     523
dtype: int64

In [ ]:
path = "/content/drive/MyDrive/세종교육/Student_performance_data _.csv"
df = pd.read_csv(path)

In [ ]:
df

StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0          1001   17       1          0                  2        19.833723   
1          1002   18       0          0                  1        15.408756   
2          1003   15       0          2                  3         4.210570   
3          1004   17       1          0                  3        10.028829   
4          1005   17       1          0                  2         4.672495   
...         ...  ...     ...        ...                ...              ...   
2387       3388   18       1          0                  3        10.680555   
2388       3389   17       0          0                  1         7.583217   
2389       3390   16       1          0                  2         6.805500   
2390       3391   16       1          1                  0        12.416653   
2391       3392   16       1          0                  2        17.819907   

      Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0            7         1                2                0       0      1   
1            0         0                1                0       0      0   
2           26         0                2                0       0      0   
3           14         0                3                1       0      0   
4           17         1                3                0       0      0   
...        ...       ...              ...              ...     ...    ...   
2387         2         0                4                1       0      0   
2388         4         1                4                0       1      0   
2389        20         0                2                0       0      0   
2390        17         0                2                0       1      1   
2391        13         0                2                0       0      0   

      Volunteering       GPA  GradeClass  
0                0  2.929196         2.0  
1                0  3.042915         1.0  
2                0  0.112602         4.0  
3                0  2.054218         3.0  
4                0  1.288061         4.0  
...            ...       ...         ...  
2387             0  3.455509         0.0  
2388             0  3.279150         4.0  
2389             1  1.142333         2.0  
2390             0  1.803297         1.0  
2391             1  2.140014         1.0  

[2392 rows x 15 columns]

In [96]:
import pickle
with open("/content/drive/MyDrive/세종교육/student_x.pkl", 'wb') as f:
  pickle.dump(x, f)
with open("/content/drive/MyDrive/세종교육/student_y.pkl", 'wb') as f:
  pickle.dump(y, f)

In [99]:
with open("/content/drive/MyDrive/세종교육/student_x.pkl", 'rb') as f:
  x = pickle.load(f)

In [ ]:
with open("/content/drive/MyDrive/세종교육/student_y.pkl", 'rb') as f:
  y = pickle.load(f)