<a href="https://colab.research.google.com/github/welcomeglory/Python/blob/master/wine_red_white.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip install tqdm
import tensorflow as tf
print(tf.__version__)
import pandas as pd
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

# Define the model class
class WineANN(tf.keras.Model):
    def __init__(self):
        super(WineANN, self).__init__()

        self.hid1 = tf.keras.layers.Dense(32,
                                          activation='relu',
                                          kernel_initializer=self.weight_initialization(),
                                          bias_initializer=self.weight_initialization())
        self.drop1 = tf.keras.layers.Dropout(0.2)

        self.hid2 = tf.keras.layers.Dense(64,
                                          activation='relu',
                                          kernel_initializer=self.weight_initialization(),
                                          bias_initializer=self.weight_initialization())
        self.drop2 = tf.keras.layers.Dropout(0.2)

        self.hid3 = tf.keras.layers.Dense(32,
                                          activation='relu',
                                          kernel_initializer=self.weight_initialization(),
                                          bias_initializer=self.weight_initialization())
        self.drop3 = tf.keras.layers.Dropout(0.2)

        self.outPut = tf.keras.layers.Dense(2,
                                            activation=None,
                                            kernel_initializer=self.weight_initialization(),
                                            bias_initializer=self.weight_initialization())

    def weight_initialization(self):
        return tf.keras.initializers.RandomNormal(mean=0., stddev=1.)

    def call(self, x, training=False):  # Forward pass
        y1 = self.hid1(x)
        d1 = self.drop1(y1, training=training)
        y2 = self.hid2(d1)
        d2 = self.drop2(y2, training=training)
        y3 = self.hid3(d2)
        d3 = self.drop3(y3, training=training)
        logits = self.outPut(d3)
        sy = tf.nn.softmax(logits)
        return logits, sy

# Loss function
@tf.function
def cross_entropy_loss(logits, y):
    return tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y))

# Optimizer and backward pass
learningRate = 0.01
optimizer = tf.optimizers.Adagrad(learningRate)

@tf.function
def backward(model, x, y):
    with tf.GradientTape() as grad:
        logits, sy = model(x, training=True)
        loss = cross_entropy_loss(logits, y)
    grads = grad.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))
    return loss

# Accuracy function
@tf.function
def accuracy(predY, y):
    correct_predictions = tf.equal(tf.argmax(predY, axis=1), tf.argmax(y, axis=1))
    acc = tf.reduce_mean(tf.cast(correct_predictions, tf.float32))
    return acc

# Training function
def train_learning(epochs, frequency, trainDataIter, model, XTest, yTest):
    y_loss = []
    for epoch in tqdm(range(epochs)):
        bx, by = next(trainDataIter)
        loss = backward(model, bx, by)
        y_loss.append(loss)
        if epoch % frequency == 0:
            predY, sy = model(bx, training=False)
            acc = accuracy(predY, by)
            print(f"Epoch: {epoch+1} ===> Loss: {loss:.4f}, Accuracy: {acc:.4f}")
    predY, sy = model(XTest, training=False)
    acc = accuracy(predY, yTest)
    print(f"Test Accuracy: {acc:.4f}")
    return y_loss

2.17.0


In [2]:
red_path = "/content/drive/MyDrive/세종교육/winequality-red.csv"
white_path = "/content/drive/MyDrive/세종교육/winequality-white.csv"
red_df = pd.read_csv(red_path, sep=';')
red_df['label'] = 0
white_df = pd.read_csv(white_path, sep=';')
white_df['label'] = 1
wine_df = pd.concat([red_df, white_df])
wine_df.reset_index(drop=True, inplace=True)
matrix = wine_df.values
X = matrix[:, :-1]
X = (X-X.min(axis=0)) / (X.max(axis=0)-X.min(axis=0))
print(X)
y = matrix[:, -1]


XTrain, XTest, yTrain, yTest = train_test_split(X, y, test_size=0.3, random_state=42)
XTrain, XTest = XTrain.astype('float32'), XTest.astype('float32')

# One-hot encode y
yTrain = tf.one_hot(yTrain.flatten(), 2)
yTest = tf.one_hot(yTest.flatten(), 2)

train_data = tf.data.Dataset.from_tensor_slices((XTrain, yTrain))
train_data = train_data.shuffle(buffer_size=XTrain.shape[0]).batch(300).repeat()
trainDataIter = iter(train_data)
# bx, by = next(trainDataIter)
# print(bx)
# print(by)

epochs = 5000
frequency = 150

model = WineANN()
y_loss = train_learning(epochs, frequency, trainDataIter, model, XTest, yTest)

# # Plot loss curve
# plt.plot(y_loss)
# plt.xlabel('Epochs')
# plt.ylabel('Loss')
# plt.title('Loss Curve')
# plt.show()

[[0.29752066 0.41333333 0.         ... 0.19101124 0.20289855 0.33333333]
 [0.33057851 0.53333333 0.         ... 0.25842697 0.26086957 0.33333333]
 [0.33057851 0.45333333 0.02409639 ... 0.24157303 0.26086957 0.33333333]
 ...
 [0.2231405  0.10666667 0.11445783 ... 0.13483146 0.20289855 0.5       ]
 [0.14049587 0.14       0.18072289 ... 0.08988764 0.69565217 0.66666667]
 [0.18181818 0.08666667 0.22891566 ... 0.05617978 0.55072464 0.5       ]]


  0%|          | 15/5000 [00:03<14:36,  5.69it/s] 

Epoch: 1 ===> Loss: 128.1373, Accuracy: 0.2433


  3%|▎         | 170/5000 [00:05<00:45, 106.69it/s]

Epoch: 151 ===> Loss: 6.4265, Accuracy: 0.8967


  7%|▋         | 333/5000 [00:06<00:30, 153.56it/s]

Epoch: 301 ===> Loss: 3.2941, Accuracy: 0.9367


 10%|▉         | 480/5000 [00:07<00:30, 148.97it/s]

Epoch: 451 ===> Loss: 3.6830, Accuracy: 0.9100


 13%|█▎        | 630/5000 [00:08<00:18, 237.20it/s]

Epoch: 601 ===> Loss: 1.6261, Accuracy: 0.9333


 16%|█▌        | 807/5000 [00:08<00:14, 288.10it/s]

Epoch: 751 ===> Loss: 1.3075, Accuracy: 0.9567


 18%|█▊        | 920/5000 [00:09<00:15, 257.84it/s]

Epoch: 901 ===> Loss: 2.1397, Accuracy: 0.9500


 21%|██▏       | 1064/5000 [00:10<00:35, 110.91it/s]

Epoch: 1051 ===> Loss: 1.7563, Accuracy: 0.9800


 24%|██▍       | 1225/5000 [00:12<00:33, 113.30it/s]

Epoch: 1201 ===> Loss: 1.5177, Accuracy: 0.9667


 27%|██▋       | 1368/5000 [00:13<00:32, 111.04it/s]

Epoch: 1351 ===> Loss: 1.4536, Accuracy: 0.9700


 31%|███       | 1551/5000 [00:14<00:15, 226.56it/s]

Epoch: 1501 ===> Loss: 0.9680, Accuracy: 0.9767


 34%|███▍      | 1693/5000 [00:15<00:12, 269.31it/s]

Epoch: 1651 ===> Loss: 1.1355, Accuracy: 0.9667


 37%|███▋      | 1835/5000 [00:15<00:11, 271.99it/s]

Epoch: 1801 ===> Loss: 0.8249, Accuracy: 0.9567


 40%|███▉      | 1999/5000 [00:16<00:11, 265.79it/s]

Epoch: 1951 ===> Loss: 0.7466, Accuracy: 0.9667


 43%|████▎     | 2142/5000 [00:16<00:10, 271.36it/s]

Epoch: 2101 ===> Loss: 0.7161, Accuracy: 0.9800


 46%|████▌     | 2286/5000 [00:17<00:10, 267.37it/s]

Epoch: 2251 ===> Loss: 0.4892, Accuracy: 0.9800


 49%|████▊     | 2427/5000 [00:17<00:11, 226.54it/s]

Epoch: 2401 ===> Loss: 0.6842, Accuracy: 0.9767


 51%|█████▏    | 2567/5000 [00:18<00:18, 133.80it/s]

Epoch: 2551 ===> Loss: 0.8923, Accuracy: 0.9667


 54%|█████▍    | 2714/5000 [00:20<00:25, 90.93it/s]

Epoch: 2701 ===> Loss: 0.8601, Accuracy: 0.9533


 57%|█████▋    | 2871/5000 [00:21<00:20, 102.27it/s]

Epoch: 2851 ===> Loss: 0.6718, Accuracy: 0.9833


 60%|██████    | 3006/5000 [00:23<00:16, 119.90it/s]

Epoch: 3001 ===> Loss: 0.5496, Accuracy: 0.9867


 63%|██████▎   | 3171/5000 [00:24<00:11, 154.42it/s]

Epoch: 3151 ===> Loss: 0.3904, Accuracy: 0.9767


 67%|██████▋   | 3326/5000 [00:25<00:10, 163.74it/s]

Epoch: 3301 ===> Loss: 0.4344, Accuracy: 0.9833


 70%|██████▉   | 3476/5000 [00:26<00:08, 173.63it/s]

Epoch: 3451 ===> Loss: 0.8618, Accuracy: 0.9733


 72%|███████▏  | 3621/5000 [00:27<00:07, 173.45it/s]

Epoch: 3601 ===> Loss: 0.4561, Accuracy: 0.9800


 76%|███████▌  | 3800/5000 [00:28<00:05, 208.31it/s]

Epoch: 3751 ===> Loss: 0.4541, Accuracy: 0.9767


 79%|███████▊  | 3928/5000 [00:28<00:07, 147.57it/s]

Epoch: 3901 ===> Loss: 0.3588, Accuracy: 0.9633


 82%|████████▏ | 4075/5000 [00:29<00:05, 161.26it/s]

Epoch: 4051 ===> Loss: 0.4030, Accuracy: 0.9767


 84%|████████▍ | 4224/5000 [00:30<00:05, 153.19it/s]

Epoch: 4201 ===> Loss: 0.4252, Accuracy: 0.9867


 88%|████████▊ | 4399/5000 [00:31<00:02, 264.91it/s]

Epoch: 4351 ===> Loss: 0.2837, Accuracy: 0.9800


 91%|█████████ | 4546/5000 [00:32<00:01, 279.81it/s]

Epoch: 4501 ===> Loss: 0.2384, Accuracy: 0.9933


 94%|█████████▍| 4694/5000 [00:32<00:01, 283.15it/s]

Epoch: 4651 ===> Loss: 0.3391, Accuracy: 0.9767


 97%|█████████▋| 4843/5000 [00:33<00:00, 274.81it/s]

Epoch: 4801 ===> Loss: 0.2753, Accuracy: 0.9867


100%|██████████| 5000/5000 [00:33<00:00, 148.38it/s]

Epoch: 4951 ===> Loss: 0.3890, Accuracy: 0.9833
Test Accuracy: 0.9790


In [ ]:
path = '/content/drive/MyDrive/세종교육/student_grade/'
model.save(path + "wineAnn_tf_2_15_version")
model.summary()

In [4]:
# model1 =tf.keras.models.load_model(path + "wineAnn_tf_2_15_version0")
print(XTest[71:72])
predY = model.predict(XTest[71:72])
print(int(tf.argmax(yTest[71:72][0], axis=0)))
print(predY[1].argmax())
predY

[[0.29752067 0.34666666 0.15662651 0.02300614 0.12292359 0.05555556
  0.19585253 0.17447464 0.44186047 0.19101124 0.26086956 0.5       ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
0
0


(array([[17.843185, 14.863704]], dtype=float32),
 array([[0.9516385 , 0.04836148]], dtype=float32))